In [1]:
from nba_api.stats.endpoints import leaguegamelog

In [2]:
import pandas as pd

In [3]:
import time

In [4]:
gamelog = leaguegamelog.LeagueGameLog(season='2025-26')

In [5]:
df = gamelog.get_data_frames()[0]

In [6]:
print (df.shape)

(2460, 29)

In [7]:
print (df.columns.tolist())

['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE']

In [8]:
df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22025,1610612745,HOU,Houston Rockets,0022500001,2025-10-21,HOU @ OKC,L,290,43,...,36,52,23,6,5,25,26,124,-1,1
1,22025,1610612747,LAL,Los Angeles Lakers,0022500002,2025-10-21,LAL vs. GSW,L,240,42,...,32,39,23,7,2,20,21,109,-10,1
2,22025,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21,OKC vs. HOU,W,290,46,...,27,38,29,12,4,12,27,125,1,1
3,22025,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21,GSW @ LAL,W,240,38,...,31,40,29,10,4,19,27,119,10,1
4,22025,1610612766,CHA,Charlotte Hornets,0022500080,2025-10-22,CHA vs. BKN,W,240,48,...,36,50,33,5,5,17,25,136,19,1

In [14]:
from nba_api.stats.endpoints import playbyplayv3

In [15]:
print(df['GAME_ID'].head(10))

0    0022500001
1    0022500002
2    0022500001
3    0022500002
4    0022500080
5    0022500081
6    0022500088
7    0022500004
8    0022500082
9    0022500085
Name: GAME_ID, dtype: object

In [16]:
time.sleep(1)

In [17]:
pbp = playbyplayv3.PlayByPlayV3(game_id='0022500001')

In [18]:
pbp_df = pbp.get_data_frames()[0]

In [19]:
print(pbp_df.shape)

(611, 24)

In [20]:
print(pbp_df.columns.tolist())

['gameId', 'actionNumber', 'clock', 'period', 'teamId', 'teamTricode', 'personId', 'playerName', 'playerNameI', 'xLegacy', 'yLegacy', 'shotDistance', 'shotResult', 'isFieldGoal', 'scoreHome', 'scoreAway', 'pointsTotal', 'location', 'description', 'actionType', 'subType', 'videoAvailable', 'shotValue', 'actionId']

In [21]:
pbp_df.head(20)

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,...,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
0,0022500001,2,PT12M00.00S,1,0,,0,,,0,...,0,0,0,,Start of 1st Period (7:44 PM EST),period,start,1,0,1
1,0022500001,4,PT12M00.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Jump Ball Holmgren vs. Adams: Tip to Thompson,Jump Ball,,1,0,2
2,0022500001,8,PT11M36.00S,1,1610612745,HOU,1630578,Sengun,A. Sengun,-179,...,,,0,v,MISS Sengun 25' 3PT Jump Shot,Missed Shot,Jump Shot,1,3,3
3,0022500001,9,PT11M31.00S,1,1610612760,OKC,1641717,Wallace,C. Wallace,0,...,,,0,h,Wallace REBOUND (Off:0 Def:1),Rebound,Unknown,1,0,4
4,0022500001,10,PT11M26.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,2,0,2,h,Holmgren 1' Cutting Layup Shot (2 PTS) (Dort 1...,Made Shot,Cutting Layup Shot,1,2,5
5,0022500001,12,PT11M26.00S,1,1610612745,HOU,1631095,Smith Jr.,J. Smith Jr.,0,...,,,0,v,Smith Jr. S.FOUL (P1.T1) (E.Dalen),Foul,Shooting,1,0,6
6,0022500001,14,PT11M26.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,3,0,3,h,Holmgren Free Throw 1 of 1 (3 PTS),Free Throw,Free Throw 1 of 1,1,0,7
7,0022500001,15,PT11M08.00S,1,1610612745,HOU,1641708,Thompson,A. Thompson,233,...,,,0,v,MISS Thompson 3PT Jump Shot,Missed Shot,Jump Shot,1,3,8
8,0022500001,16,PT11M04.00S,1,1610612745,HOU,1631095,Smith Jr.,J. Smith Jr.,0,...,,,0,v,Smith Jr. REBOUND (Off:1 Def:0),Rebound,Unknown,1,0,9
9,0022500001,17,PT11M02.00S,1,1610612745,HOU,1631095,Smith Jr.,J. Smith Jr.,-7,...,3,2,5,v,Smith Jr. 1' Putback Layup (2 PTS),Made Shot,Putback Layup Shot,1,2,10
10,0022500001,18,PT10M50.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,64,...,5,2,7,h,Holmgren 7' Floating Jump Shot (5 PTS) (Wallac...,Made Shot,Floating Jump shot,1,2,11
11,0022500001,20,PT10M40.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,0,...,,,0,h,Holmgren Violation:Kicked Ball (Z.Zarba),Violation,Kicked Ball,0,0,12
12,0022500001,21,PT10M24.00S,1,1610612745,HOU,1630578,Sengun,A. Sengun,72,...,,,0,v,MISS Sengun 15' Pullup Jump Shot,Missed Shot,Pullup Jump shot,1,2,13
13,0022500001,23,PT10M24.00S,1,0,,1610612745,,,0,...,,,0,v,Rockets Rebound,Rebound,Unknown,0,0,14
14,0022500001,24,PT10M24.00S,1,0,,1610612745,,,0,...,,,0,v,Rockets Turnover: Shot Clock (T#1),Turnover,Shot Clock Turnover,1,0,15
15,0022500001,25,PT10M11.00S,1,1610612760,OKC,1628983,Gilgeous-Alexander,S. Gilgeous-Alexander,0,...,,,0,h,Gilgeous-Alexander Bad Pass Turnover (P1.T1),Turnover,Bad Pass,1,0,16
16,0022500001,25,PT10M11.00S,1,1610612745,HOU,1630578,Sengun,A. Sengun,0,...,,,0,v,Sengun STEAL (1 STL),,,1,0,17
17,0022500001,27,PT10M07.00S,1,1610612745,HOU,201142,Durant,K. Durant,0,...,5,4,9,v,Durant Running Dunk (2 PTS) (Thompson 1 AST),Made Shot,Running Dunk Shot,1,2,18
18,0022500001,29,PT09M52.00S,1,1610612760,OKC,1631096,Holmgren,C. Holmgren,59,...,7,4,11,h,Holmgren 13' Turnaround Fadeaway (7 PTS),Made Shot,Turnaround Fadeaway shot,1,2,19
19,0022500001,30,PT09M35.00S,1,1610612745,HOU,1631095,Smith Jr.,J. Smith Jr.,164,...,7,7,14,v,Smith Jr. 26' 3PT Jump Shot (5 PTS) (Thompson ...,Made Shot,Jump Shot,1,3,20